[workspace]
resolver = "2"
members = [
    "crates/deckery-pin-set",
    "crates/deckery-pam",
    "crates/deckery-pam-test",
]

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/Plasma-Deckery/deckery-auth"

[workspace.dependencies]
argon2 = "0.5"
rand = "0.8"
anyhow = "1"
libc = "0.2"
